CREATE TABLE [dbo].[Tournaments] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [LeagueId]             UNIQUEIDENTIFIER NOT NULL,
    [CreatedByUserId]      UNIQUEIDENTIFIER NOT NULL,
    [AttachedTournamentId] UNIQUEIDENTIFIER NULL,
    [DateCreated]          DATETIME         NOT NULL,
    [DateDeleted]          DATETIME         NULL,
    [Name]                 NVARCHAR (100)   NOT NULL,
    [Date]                 DATETIME         NOT NULL,
    [GameType]             INT              NOT NULL,
    [Description]          NVARCHAR (1000)  NOT NULL,
    [DateEnded]            DATETIME         NULL,
    [IsHidden]             BIT              NOT NULL,
    [IsRunning]            BIT              NOT NULL,
    [StructureId]          UNIQUEIDENTIFIER NOT NULL,
    [BuyInPrize]           INT              NOT NULL,
    [RebuyPrize]           INT              NOT NULL,
    [AddOnPrize]           INT              NOT NULL,
    [BuyInStack]           INT              NOT NULL,
    [RebuyStack]           INT              NOT NULL,
    [AddOnStack]           INT              NOT NULL,
    [BonusStack]           INT              NOT NULL,
    [IsFullPointed]        BIT              NOT NULL,
    [IsLeague]             BIT              NOT NULL,
    [GTD]                  INT              NOT NULL,
    [ReBuyCount]           INT              NOT NULL,
    [IsFood]               BIT              NOT NULL,
    [BountyDesc]           NVARCHAR (100)   NOT NULL,
    [SpecialAddonPrize]    INT              NOT NULL,
    [SpecialAddonStack]    INT              NOT NULL,
    [FullStackBonus]       INT              NOT NULL,
    [IsPercentageBonus]    BIT              NOT NULL,
    [LogicType]            INT              NOT NULL,
    [IsHighlighted]        BIT              CONSTRAINT [DF_Tournaments_IsHighlighted] DEFAULT ((0)) NOT NULL,
    [RakePercentage]       INT              NOT NULL,
    [LeaguePercentage]     INT              NOT NULL,
    [ReEntryCount]         INT              NULL,
    CONSTRAINT [PK_Tournaments] PRIMARY KEY CLUSTERED ([Id] ASC)
);

