//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubArcada.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=PokerSystem;Persist Security Info=True;" +
            "User ID=PokerTimer")]
        public string PokerSystemConnectionString {
            get {
                return ((string)(this["PokerSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;Persist Security Info=True;Use" +
            "r ID=ACDB_user")]
        public string ACDB_DEVConnectionString {
            get {
                return ((string)(this["ACDB_DEVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;User ID=ACDB_User")]
        public string ACDB_DEVConnectionString1 {
            get {
                return ((string)(this["ACDB_DEVConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;User ID=ACDB_user")]
        public string ACDB_DEVConnectionString2 {
            get {
                return ((string)(this["ACDB_DEVConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;User ID=ACDB_user;Password=ULw" +
            "EsjcpDxjKLbL5")]
        public string ACDB_DEVConnectionString3 {
            get {
                return ((string)(this["ACDB_DEVConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;User ID=PeterVarga")]
        public string ACDB_DEVConnectionString4 {
            get {
                return ((string)(this["ACDB_DEVConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;Persist Security Info=True;Use" +
            "r ID=PeterVarga")]
        public string ACDB_DEVConnectionString5 {
            get {
                return ((string)(this["ACDB_DEVConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;Persist Security Info=True;Use" +
            "r ID=PeterVarga;Password=Vape6931")]
        public string ACDB_DEVConnectionString6 {
            get {
                return ((string)(this["ACDB_DEVConnectionString6"]));
            }
        }
    }
}
