<?xml version="1.0" encoding="utf-8"?><Database Name="ACDB_DEV" Class="CADBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=82.119.117.77;Initial Catalog=ACDB_DEV;User ID=PeterVarga" SettingsObjectName="ClubArcada.Common.Properties.Settings" SettingsPropertyName="ACDB_DEVConnectionString4" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsPersonal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AutoReturnType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsWallet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AdminLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsTestUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BusinessUnitId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_CashPlayer" Member="CashPlayers" ThisKey="Id" OtherKey="UserId" Type="CashPlayer" />
      <Association Name="User_Request" Member="Requests" ThisKey="Id" OtherKey="CreatedByUserId" Type="Request" />
      <Association Name="User_Shift" Member="Shifts" ThisKey="Id" OtherKey="UserId" Type="Shift" />
      <Association Name="User_Ticket" Member="Tickets" ThisKey="Id" OtherKey="UserId" Type="Ticket" />
      <Association Name="User_TournamentPlayer" Member="TournamentPlayers" ThisKey="Id" OtherKey="UserId" Type="TournamentPlayer" />
      <Association Name="User_Transaction" Member="Transactions" ThisKey="Id" OtherKey="UserId" Type="Transaction" />
      <Association Name="User_Accounting" Member="Accountings" ThisKey="Id" OtherKey="UserId" Type="Accounting" />
    </Type>
  </Table>
  <Table Name="dbo.AuditHistories" Member="AuditHistories">
    <Type Name="AuditHistory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Banners" Member="Banners">
    <Type Name="Banner">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeactivated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SortNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessUnits" Member="BusinessUnits">
    <Type Name="BusinessUnit">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HasCalendar" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.CashIns" Member="CashIns">
    <Type Name="CashIn">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CashPlayer_CashIn" Member="CashPlayer" ThisKey="PlayerId" OtherKey="Id" Type="CashPlayer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CashOuts" Member="CashOuts">
    <Type Name="CashOut">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="CashPlayer_CashOut" Member="CashPlayer" ThisKey="PlayerId" OtherKey="Id" Type="CashPlayer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CashPlayers" Member="CashPlayers">
    <Type Name="CashPlayer">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TournamentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CashTableId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="CashPlayer_CashIn" Member="CashIns" ThisKey="Id" OtherKey="PlayerId" Type="CashIn" />
      <Association Name="CashPlayer_CashOut" Member="CashOuts" ThisKey="Id" OtherKey="PlayerId" Type="CashOut" />
      <Association Name="User_CashPlayer" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Tournament_CashPlayer" Member="Tournament" ThisKey="TournamentId" OtherKey="Id" Type="Tournament" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CashStates" Member="CashStates">
    <Type Name="CashState">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TournamentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Input" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="LastInput" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Rake" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Jackpot" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Tournament_CashState" Member="Tournament" ThisKey="TournamentId" OtherKey="Id" Type="Tournament" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CashTables" Member="CashTables">
    <Type Name="CashTable">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TournamentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="GameType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateClosed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Tournament_CashTable" Member="Tournament" ThisKey="TournamentId" OtherKey="Id" Type="Tournament" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Image">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Extension" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Jackpots" Member="Jackpots">
    <Type Name="Jackpot">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateStarted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateStopped" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WinUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FloorUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Leagues" Member="Leagues">
    <Type Name="League">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Requests" Member="Requests">
    <Type Name="Request">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCompleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Request" Member="User" ThisKey="CreatedByUserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shifts" Member="Shifts">
    <Type Name="Shift">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BusinessUnitId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Shift" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StructureDetails" Member="StructureDetails">
    <Type Name="StructureDetail">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StructureId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ante" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsLastLevel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Structure_StructureDetail" Member="Structure" ThisKey="StructureId" OtherKey="Id" Type="Structure" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Structures" Member="Structures">
    <Type Name="Structure">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Structure_StructureDetail" Member="StructureDetails" ThisKey="Id" OtherKey="StructureId" Type="StructureDetail" />
    </Type>
  </Table>
  <Table Name="dbo.TicketItems" Member="TicketItems">
    <Type Name="TicketItem">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TicketId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Ticket_TicketItem" Member="Ticket" ThisKey="TicketId" OtherKey="Id" Type="Ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tickets" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TournamentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Identification" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Ticket_TicketItem" Member="TicketItems" ThisKey="Id" OtherKey="TicketId" Type="TicketItem" />
      <Association Name="User_Ticket" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Tournament_Ticket" Member="Tournament" ThisKey="TournamentId" OtherKey="Id" Type="Tournament" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TournamentCashouts" Member="TournamentCashouts">
    <Type Name="TournamentCashout">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TournamentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Rake" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Prizepool" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Food" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Dotation" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Places" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RunnerHelp" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Tips" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="CGBank" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="APCBank" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Floor" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Dealer" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="Tournament_TournamentCashout" Member="Tournament" ThisKey="TournamentId" OtherKey="Id" Type="Tournament" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TournamentPlayers" Member="TournamentPlayers">
    <Type Name="TournamentPlayer">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TournamentId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Rank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PokerCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StraightFlushCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoyalFlushCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReEntryCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAddOnCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StackBonusSum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="User_TournamentPlayer" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Tournament_TournamentPlayer" Member="Tournament" ThisKey="TournamentId" OtherKey="Id" Type="Tournament" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tournaments" Member="Tournaments">
    <Type Name="Tournament">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LeagueId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AttachedTournamentId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GameType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="DateEnded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsRunning" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="StructureId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BuyInPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RebuyPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyInStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RebuyStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BonusStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFullPointed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLeague" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GTD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFood" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BountyDesc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAddonPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAddonStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullStackBonus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPercentageBonus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LogicType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsHighlighted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RakePercentage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LeaguePercentage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReEntryCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tournament_CashPlayer" Member="CashPlayers" ThisKey="Id" OtherKey="TournamentId" Type="CashPlayer" />
      <Association Name="Tournament_CashState" Member="CashStates" ThisKey="Id" OtherKey="TournamentId" Type="CashState" />
      <Association Name="Tournament_CashTable" Member="CashTables" ThisKey="Id" OtherKey="TournamentId" Type="CashTable" />
      <Association Name="Tournament_Ticket" Member="Tickets" ThisKey="Id" OtherKey="TournamentId" Type="Ticket" />
      <Association Name="Tournament_TournamentCashout" Member="TournamentCashouts" ThisKey="Id" OtherKey="TournamentId" Type="TournamentCashout" />
      <Association Name="Tournament_TournamentPlayer" Member="TournamentPlayers" ThisKey="Id" OtherKey="TournamentId" Type="TournamentPlayer" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AttachedTransactionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Amount2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TransactionType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAddedToDB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUsed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DatePayed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByApp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Transaction" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Accountings" Member="Accountings">
    <Type Name="Accounting">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="IsLoggedInTournament" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLoggedInCash" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateLastReset" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="User_Accounting" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_get_audit_history" Method="sp_get_audit_history">
    <Parameter Name="count" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_get_audit_historyResult">
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUser" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_wallet_transactions" Method="sp_get_wallet_transactions">
    <Parameter Name="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="dateTimeFrom" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_get_wallet_transactionsResult">
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreatedByApp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateAddedToDB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TransactionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(304) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_balance_user_list" Method="sp_get_balance_user_list">
    <Parameter Name="searchString" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="sp_get_balance_user_listResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AutoReturnType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPersonal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsTestUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsWallet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsBlocked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_cash_league_ladder" Method="sp_get_cash_league_ladder">
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" />
    <Parameter Name="LeagueId" Parameter="leagueId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="DateFrom" Parameter="dateFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateTo" Parameter="dateTo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_get_cash_league_ladderResult">
      <Column Name="userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="points" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="playcount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nickname" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_cash_report" Method="sp_get_cash_report">
    <Parameter Name="DateFrom" Parameter="dateFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateTo" Parameter="dateTo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_get_cash_reportResult">
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Jackpot" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Rake" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
      <Column Name="Tips" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="RunnerHelp" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_poker_league_ladder" Method="sp_get_poker_league_ladder">
    <Parameter Name="Count" Parameter="count" Type="System.Int32" DbType="Int" />
    <Parameter Name="LeagueId" Parameter="leagueId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="DateFrom" Parameter="dateFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DateTo" Parameter="dateTo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_get_poker_league_ladderResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="PlayCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_requests" Method="sp_get_requests">
    <ElementType Name="sp_get_requestsResult">
      <Column Name="DateCompleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserCreated" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
      <Column Name="UserCompleted" Type="System.String" DbType="NVarChar(201)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_shifts" Method="sp_get_shifts">
    <Parameter Name="businessUnitId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="dateFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="dateTo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_get_shiftsResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_tournament_results" Method="sp_get_tournament_results">
    <Parameter Name="tournamentId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="sp_get_tournament_resultsResult">
      <Column Name="Rank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="IsPersonal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReEntryCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RoyalFlushCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StraightFlushCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PokerCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_tournaments" Method="sp_get_tournaments">
    <Parameter Name="onlyFuture" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="sp_get_tournamentsResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PlayerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GameType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRunning" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="DateEnded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsFullPointed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLeague" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BuyInPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyInStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BonusStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GTD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFood" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BountyDesc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAddonPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAddonStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullStackBonus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPercentageBonus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateDeleted" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AddOns" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReBuys" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrizePool" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="EntryCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_user_balance" Method="sp_get_user_balance">
    <Parameter Name="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="sp_get_user_balanceResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_user_transaction_history" Method="sp_get_user_transaction_history">
    <Parameter Name="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="sp_get_user_transaction_historyResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TransactionType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateAddedToDB" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUsed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Amount2" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DatePayed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateCreated1" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByApp" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttachedTransactionId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(201) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_get_tournament_report" Method="sp_get_tournament_report">
    <Parameter Name="dateFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="dateTo" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_get_tournament_reportResult">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PlayerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EntryCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GameType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsRunning" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="IsFullPointed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLeague" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BuyInPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BuyInStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddOnStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BonusStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GTD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReBuyCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsFood" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BountyDesc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAddonPrize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpecialAddonStack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullStackBonus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsPercentageBonus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsHidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddOns" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReBuys" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="League" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Rake" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Dotation" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>